# -*- coding: utf-8 -*-
"""d_operator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jsjbxMXPiYucbn3-PoNc49sSygEpcLNV
"""

"""
SymPy 外微分算子 (Exterior Derivative) 示範
展示微分形式和外微分的計算
"""

from sympy import symbols, sin, cos, sqrt, simplify, Symbol
from sympy.diffgeom import Manifold, Patch, CoordSystem, TensorProduct
from sympy.diffgeom import WedgeProduct

print("=" * 70)
print("外微分算子 (Exterior Derivative) 示範")
print("=" * 70)

print("\n" + "=" * 70)
print("1. 建立流形和座標系統")
print("=" * 70)

# 建立 3 維流形
m = Manifold('M', 3)
patch = Patch('P', m)

# 定義笛卡爾座標系統
x_sym = Symbol('x', real=True)
y_sym = Symbol('y', real=True)
z_sym = Symbol('z', real=True)

cart = CoordSystem('cart', patch, [x_sym, y_sym, z_sym])
x, y, z = cart.coord_functions()
dx, dy, dz = cart.base_oneforms()

print(f"座標系統: (x, y, z)")
print(f"基底 1-形式: dx={dx}, dy={dy}, dz={dz}")

print("\n" + "=" * 70)
print("2. 函數的外微分 (0-形式 → 1-形式)")
print("=" * 70)

# 定義一個函數 (0-形式)
# 使用符號變數而非座標函數
x_var = Symbol('x', real=True)
y_var = Symbol('y', real=True)
z_var = Symbol('z', real=True)

f = x_var**2 + y_var**2 + z_var**2
print(f"\n函數 f = {f}")

# 計算偏導數
df_dx = f.diff(x_var)
df_dy = f.diff(y_var)
df_dz = f.diff(z_var)

print("\n偏導數:")
print(f"∂f/∂x = {df_dx}")
print(f"∂f/∂y = {df_dy}")
print(f"∂f/∂z = {df_dz}")

# 構造外微分 df
df_form = df_dx*dx + df_dy*dy + df_dz*dz
print(f"\n外微分 df:")
print(f"df = ∂f/∂x dx + ∂f/∂y dy + ∂f/∂z dz")
print(f"df = {df_form}")

print("\n物理意義:")
print("• df 是函數 f 的梯度")
print("• df 是一個 1-形式(余切向量場)")
print("• df 可以作用在向量場上給出方向導數")

print("\n" + "=" * 70)
print("3. 1-形式的外微分 (1-形式 → 2-形式)")
print("=" * 70)

# 定義一個 1-形式的係數
# omega1 = y dx + x dy + z dz
# 係數函數
P = y_var
Q = x_var
R = z_var

print(f"\n1-形式 ω = y dx + x dy + z dz")

# 計算外微分 dω
# d(P dx) = (∂P/∂y dy + ∂P/∂z dz) ∧ dx
# d(Q dy) = (∂Q/∂x dx + ∂Q/∂z dz) ∧ dy
# d(R dz) = (∂R/∂x dx + ∂R/∂y dy) ∧ dz

print("\n計算外微分 dω:")
print("d(y dx) = dy ∧ dx")
print("d(x dy) = dx ∧ dy")
print("d(z dz) = 0 (係數是 z,不依賴 x,y)")

# dy ∧ dx = -dx ∧ dy (反對稱性)
print(f"\ndω = dy∧dx + dx∧dy")
print(f"   = -dx∧dy + dx∧dy  (反對稱性)")
print(f"   = 0")

print("\n這個 1-形式的外微分為零!")
print("可以證明 ω = d(xy + z²/2)")

print("\n" + "=" * 70)
print("4. 非恰當 1-形式的例子")
print("=" * 70)

# 另一個 1-形式: omega2 = y dx - x dy
P2 = y_var
Q2 = -x_var

print(f"\n1-形式 ω₂ = y dx - x dy")

print("\n計算外微分 dω₂:")
print("d(y dx) = (∂y/∂y) dy ∧ dx = dy ∧ dx")
print("d(-x dy) = (∂(-x)/∂x) dx ∧ dy = -dx ∧ dy")

# 計算偏導數
dP2_dy = P2.diff(y_var)  # = 1
dQ2_dx = Q2.diff(x_var)  # = -1

print(f"\ndω₂ = dy∧dx - dx∧dy")
print(f"    = -dx∧dy - dx∧dy")
print(f"    = -2 dx∧dy")

print("\n這給出一個非零的 2-形式!")
print("ω₂ 對應於極座標中的 dθ (角度微分)")
print("在單位圓上積分: ∮ ω₂ = 2π (非零)")

print("\n" + "=" * 70)
print("5. 2-形式的外微分 (2-形式 → 3-形式)")
print("=" * 70)

# 定義一個 2-形式的係數
# Ω = x dy∧dz + y dz∧dx + z dx∧dy
print(f"\n2-形式 Ω = x dy∧dz + y dz∧dx + z dx∧dy")

print("\n計算外微分 dΩ:")
print("d(x dy∧dz) = (∂x/∂x) dx∧dy∧dz = dx∧dy∧dz")
print("d(y dz∧dx) = (∂y/∂y) dy∧dz∧dx")
print("           = dy∧dz∧dx = dx∧dy∧dz (重排)")
print("d(z dx∧dy) = (∂z/∂z) dz∧dx∧dy")
print("           = dz∧dx∧dy = dx∧dy∧dz (重排)")

# 計算偏導數
dx_coeff = x_var.diff(x_var)  # = 1
dy_coeff = y_var.diff(y_var)  # = 1
dz_coeff = z_var.diff(z_var)  # = 1

print("\ndΩ = dx∧dy∧dz + dx∧dy∧dz + dx∧dy∧dz")
print("   = 3 dx∧dy∧dz")

print("\n這是體積形式的 3 倍!")
print("這個 2-形式對應向量場 F = (x, y, z) = r")

print("\n" + "=" * 70)
print("6. 外微分的性質")
print("=" * 70)

print("\n(1) 線性:")
print("    d(ω + η) = dω + dη")
print("    d(cω) = c dω  (c 是常數)")

print("\n(2) 萊布尼茨法則:")
print("    d(ω ∧ η) = dω ∧ η + (-1)^p ω ∧ dη")
print("    其中 ω 是 p-形式")

print("\n(3) 冪零性 (最重要!):")
print("    d(dω) = 0")
print("    即 d² = 0")

print("\n證明 d² = 0 的例子:")
print("取函數 f = x²y")
f_test = x_var**2 * y_var
print(f"f = {f_test}")

# 計算 df
df_test_dx = f_test.diff(x_var)  # 2xy
df_test_dy = f_test.diff(y_var)  # x²
print(f"\ndf = {df_test_dx} dx + {df_test_dy} dy")

# 計算 d(df)
# d(2xy dx) 需要計算 2xy 的外微分與 dx 的楔積
# ∂(2xy)/∂y = 2x
print(f"\nd(df):")
print(f"  d(2xy dx) = (∂(2xy)/∂y) dy ∧ dx = 2x dy∧dx = -2x dx∧dy")
print(f"  d(x² dy) = (∂(x²)/∂x) dx ∧ dy = 2x dx∧dy")

print(f"\n因此 d(df) = -2x dx∧dy + 2x dx∧dy = 0 ✓")
print("\n這驗證了 d² = 0 的性質!")

print("\n" + "=" * 70)
print("7. 閉形式與恰當形式")
print("=" * 70)

print("\n定義:")
print("• 閉形式 (Closed form): dω = 0")
print("• 恰當形式 (Exact form): ω = dη (存在 η 使得)")

print("\n重要關係:")
print("• 所有恰當形式都是閉形式 (因為 d² = 0)")
print("• 但不是所有閉形式都是恰當形式!")

print("\nPoincaré 引理:")
print("在可縮空間上,所有閉形式都是恰當形式")

print("\nde Rham 上同調:")
print("H^p(M) = {閉 p-形式} / {恰當 p-形式}")
print("測量空間的拓撲性質")

print("\n例子:")
print("• 在 R³ 上: 所有閉形式都是恰當形式")
print("• 在圓周 S¹ 上: dθ 是閉的但不是恰當的")
print("• 在環面 T² 上: 有 2 個獨立的閉但不恰當的 1-形式")

print("\n" + "=" * 70)
print("8. 斯托克斯定理 (Stokes' Theorem)")
print("=" * 70)

print("\n最一般的形式:")
print("∫_M dω = ∫_∂M ω")
print("\n其中:")
print("• M 是流形")
print("• ∂M 是 M 的邊界")
print("• ω 是 (n-1)-形式")
print("• dω 是 n-形式")

print("\n特殊情況:")

print("\n(1) 基本定理 (1維):")
print("    ∫_a^b f'(x) dx = f(b) - f(a)")

print("\n(2) 格林定理 (2維):")
print("    ∫∫_D (∂Q/∂x - ∂P/∂y) dx dy = ∮_∂D P dx + Q dy")

print("\n(3) 散度定理 (3維):")
print("    ∫∫∫_V ∇·F dV = ∮∮_∂V F·dS")

print("\n(4) 旋度定理 (3維):")
print("    ∫∫_S (∇×F)·dS = ∮_∂S F·dr")

print("\n所有這些都是斯托克斯定理的特例!")

print("\n" + "=" * 70)
print("9. 向量微積分與微分形式的對應")
print("=" * 70)

print("\n在 R³ 中:")

print("\n梯度 ↔ 外微分:")
print("  函數 f → 1-形式 df")
print("  grad f = (∂f/∂x, ∂f/∂y, ∂f/∂z)")
print("  df = (∂f/∂x)dx + (∂f/∂y)dy + (∂f/∂z)dz")

print("\n旋度 ↔ 外微分:")
print("  1-形式 ω → 2-形式 dω")
print("  如果 ω = P dx + Q dy + R dz")
print("  則 dω 對應 curl(P,Q,R)")

print("\n散度 ↔ 外微分:")
print("  2-形式 Ω → 3-形式 dΩ")
print("  dΩ 對應散度乘以體積形式")

print("\n恆等式:")
print("  curl(grad f) = 0  ↔  d(df) = 0")
print("  div(curl F) = 0   ↔  d(dω) = 0")

print("\n" + "=" * 70)
print("10. 物理應用")
print("=" * 70)

print("\n電磁學:")
print("• 電磁場張量 F 是 2-形式")
print("• Maxwell 方程: dF = 0 (無磁單極)")
print("•              d(*F) = *J (電荷守恆)")

print("\n熱力學:")
print("• dU = TdS - PdV (熱力學第一定律)")
print("• 如果 dω = 0,則過程可逆")

print("\n流體力學:")
print("• 渦量 ω 是 2-形式")
print("• Kelvin 環流定理: dω/dt = 0")

print("\n廣義相對論:")
print("• 曲率 2-形式 Ω")
print("• Bianchi 恆等式: dΩ = 0")

print("\n量子力學:")
print("• Berry 相位")
print("• 規範場論")
print("• 拓撲相")

print("\n" + "=" * 70)
print("11. 極座標中的例子")
print("=" * 70)

print(f"\n極座標: (r, θ)")
print("注意: 在 2D 中我們只需要 r 和 θ")

print("\n角度 1-形式:")
print("在直角座標中: dθ = (1/(x²+y²))(-y dx + x dy)")
print("這對應於我們之前的 ω₂ = y dx - x dy (差一個因子)")

print("\n外微分:")
print("d(dθ) = 0 (根據 d² = 0)")

print("\n但在繞原點的閉路積分:")
print("∮ dθ = 2π (繞原點一圈)")

print("\n這是非恰當閉形式的經典例子!")
print("• 在 R² - {0} 上 dθ 是閉的 (d(dθ)=0)")
print("• 但 dθ 不是恰當的(沒有單值的 θ 函數)")
print("• 反映了空間的非單連通拓撲")
print("• 原點處有一個「洞」")

print("\n拓撲意義:")
print("• de Rham 上同調 H¹(R²-{0}) ≠ 0")
print("• 這個空間拓撲上等價於圓周 S¹")
print("• dθ 代表了這個圓周的生成元")

print("\n" + "=" * 70)
print("12. Cartan 結構方程")
print("=" * 70)

print("\n在微分幾何中,Cartan 使用外微分描述曲率:")

print("\n第一結構方程:")
print("dθ^i = -ω^i_j ∧ θ^j  (撓率方程)")

print("\n第二結構方程:")
print("dω^i_j = -ω^i_k ∧ ω^k_j + Ω^i_j  (曲率方程)")

print("\n其中:")
print("• θ^i: 基底 1-形式")
print("• ω^i_j: 聯絡 1-形式")
print("• Ω^i_j: 曲率 2-形式")

print("\nBianchi 恆等式:")
print("dΩ^i_j = Ω^i_k ∧ ω^k_j - ω^i_k ∧ Ω^k_j")

print("\n在無撓率情況:")
print("dθ^i = -ω^i_j ∧ θ^j")
print("dω^i_j + ω^i_k ∧ ω^k_j = Ω^i_j")

print("\n" + "=" * 70)
print("示範完成!")
print("=" * 70)

print("\n摘要:")
print("• 外微分是微分形式理論的核心運算")
print("• d² = 0 是最重要的性質")
print("• 閉形式和恰當形式與拓撲相關")
print("• 斯托克斯定理統一了所有積分定理")
print("• 微分形式提供了座標無關的微積分")
print("• 在現代幾何、物理和拓撲中不可或缺")

print("\n為什麼使用微分形式?")
print("✓ 座標無關 (幾何不變)")
print("✓ 統一的積分理論")
print("✓ 優雅的數學結構")
print("✓ 自然地描述物理定律")
print("✓ 連接幾何與拓撲")
print("✓ 便於計算機符號計算")