# -*- coding: utf-8 -*-
"""schwarzschild.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hj0_BAN22WMAsbksUPVP0olnGrYeyxs1
"""

"""
史瓦西度規 (Schwarzschild Metric) 示範
這是廣義相對論中球對稱、靜態黑洞的時空解
"""

from sympy import symbols, sin, cos, sqrt, simplify, pi, Symbol, Function
from sympy.diffgeom import Manifold, Patch, CoordSystem, TensorProduct
from sympy.diffgeom import metric_to_Christoffel_2nd, metric_to_Ricci_components
from sympy import Matrix, tensorproduct, eye

print("=" * 70)
print("史瓦西度規 (Schwarzschild Metric)")
print("描述球對稱、靜態、真空中的黑洞時空")
print("=" * 70)

print("\n" + "=" * 70)
print("1. 建立 4 維時空流形")
print("=" * 70)

# 建立 4 維時空流形
spacetime = Manifold('M', 4)
patch = Patch('P', spacetime)

# 定義史瓦西座標 (t, r, theta, phi)
t_sym = Symbol('t', real=True)  # 時間座標
r_sym = Symbol('r', positive=True, real=True)  # 徑向座標
theta_sym = Symbol('theta', real=True)  # 極角
phi_sym = Symbol('phi', real=True)  # 方位角

schwarzschild = CoordSystem('schwarzschild', patch,
                           [t_sym, r_sym, theta_sym, phi_sym])

# 取得座標函數
t, r, theta, phi = schwarzschild.coord_functions()

# 取得基底 1-形式
dt, dr, dtheta, dphi = schwarzschild.base_oneforms()

# 取得基底向量
e_t, e_r, e_theta, e_phi = schwarzschild.base_vectors()

print(f"座標系統: 史瓦西座標 (t, r, θ, φ)")
print(f"t = {t} (時間座標)")
print(f"r = {r} (徑向座標)")
print(f"θ = {theta} (極角)")
print(f"φ = {phi} (方位角)")

print("\n" + "=" * 70)
print("2. 定義史瓦西度規張量")
print("=" * 70)

# 史瓦西半徑參數 (質量參數)
# r_s = 2GM/c² (在自然單位 c=G=1 下，r_s = 2M)
M = Symbol('M', positive=True, real=True)  # 黑洞質量
r_s = 2*M  # 史瓦西半徑

print(f"\n質量參數: M = {M}")
print(f"史瓦西半徑: r_s = 2M = {r_s}")

# 度規函數
g_tt = -(1 - r_s/r)  # g_00
g_rr = 1/(1 - r_s/r)  # g_11
g_thetatheta = r**2  # g_22
g_phiphi = r**2 * sin(theta)**2  # g_33

print("\n史瓦西度規的非零分量:")
print(f"g_tt = {g_tt}")
print(f"g_rr = {g_rr}")
print(f"g_θθ = {g_thetatheta}")
print(f"g_φφ = {g_phiphi}")

# 構造度規張量
# ds² = g_tt dt² + g_rr dr² + g_θθ dθ² + g_φφ dφ²
metric = (g_tt * TensorProduct(dt, dt) +
          g_rr * TensorProduct(dr, dr) +
          g_thetatheta * TensorProduct(dtheta, dtheta) +
          g_phiphi * TensorProduct(dphi, dphi))

print("\n完整的史瓦西線元:")
print("ds² = -(1-2M/r)dt² + (1-2M/r)⁻¹dr² + r²dθ² + r²sin²(θ)dφ²")

print("\n" + "=" * 70)
print("3. 重要物理特性")
print("=" * 70)

print("\n事件視界 (Event Horizon):")
print(f"  位置: r = r_s = {r_s}")
print(f"  當 r = r_s 時，g_tt = 0, g_rr → ∞")
print(f"  這是黑洞的邊界，光也無法逃脫")

print("\n奇異點 (Singularity):")
print(f"  位置: r = 0")
print(f"  這是真正的時空奇異點，曲率發散")

print("\n漸近平坦性:")
print(f"  當 r → ∞ 時，度規趨近閔可夫斯基度規")
print(f"  g_tt → -1, g_rr → 1, g_θθ → r², g_φφ → r²sin²(θ)")

print("\n" + "=" * 70)
print("4. 計算 Christoffel 符號 (聯絡係數)")
print("=" * 70)

print("\n計算中... (這可能需要一些時間)")

# 計算 Christoffel 符號
christoffel = metric_to_Christoffel_2nd(metric)

print("\n一些重要的非零 Christoffel 符號:")

# Γ^t_tr
gamma_t_tr = simplify(christoffel[0, 0, 1])
print(f"Γ^t_tr = {gamma_t_tr}")

# Γ^r_tt
gamma_r_tt = simplify(christoffel[1, 0, 0])
print(f"Γ^r_tt = {gamma_r_tt}")

# Γ^r_rr
gamma_r_rr = simplify(christoffel[1, 1, 1])
print(f"Γ^r_rr = {gamma_r_rr}")

# Γ^r_θθ
gamma_r_thetatheta = simplify(christoffel[1, 2, 2])
print(f"Γ^r_θθ = {gamma_r_thetatheta}")

# Γ^r_φφ
gamma_r_phiphi = simplify(christoffel[1, 3, 3])
print(f"Γ^r_φφ = {gamma_r_phiphi}")

# Γ^θ_rθ
gamma_theta_rtheta = simplify(christoffel[2, 1, 2])
print(f"Γ^θ_rθ = {gamma_theta_rtheta}")

# Γ^θ_φφ
gamma_theta_phiphi = simplify(christoffel[2, 3, 3])
print(f"Γ^θ_φφ = {gamma_theta_phiphi}")

# Γ^φ_rφ
gamma_phi_rphi = simplify(christoffel[3, 1, 3])
print(f"Γ^φ_rφ = {gamma_phi_rphi}")

# Γ^φ_θφ
gamma_phi_thetaphi = simplify(christoffel[3, 2, 3])
print(f"Γ^φ_θφ = {gamma_phi_thetaphi}")

print("\n" + "=" * 70)
print("5. 計算 Ricci 張量")
print("=" * 70)

print("\n計算中... (這需要較長時間)")

# 計算 Ricci 張量分量
ricci = metric_to_Ricci_components(metric)

print("\n驗證真空場方程式 R_μν = 0:")
print("(史瓦西解是愛因斯坦真空場方程式的解)")

all_zero = True
for i in range(4):
    for j in range(i, 4):
        component = simplify(ricci[i, j])
        if component != 0:
            print(f"R_{i}{j} = {component}")
            all_zero = False

if all_zero:
    print("\n✓ 所有 Ricci 張量分量都為零!")
    print("✓ 這證實了史瓦西解滿足愛因斯坦真空場方程式")
    print("  R_μν = 0")
else:
    print("\n(某些分量可能需要進一步簡化)")

print("\n" + "=" * 70)
print("6. 物理應用")
print("=" * 70)

print("\n史瓦西度規的重要應用:")
print("• 計算黑洞周圍的測地線 (自由落體粒子軌道)")
print("• 預測光線在重力場中的偏折")
print("• 計算重力紅移效應")
print("• 描述黑洞的事件視界")
print("• 霍金輻射的理論基礎")

print("\n測地線方程 (自由落體粒子):")
print("d²x^μ/dτ² + Γ^μ_αβ (dx^α/dτ)(dx^β/dτ) = 0")
print("其中 τ 是固有時間")

print("\n光線軌跡 (null geodesic):")
print("滿足 ds² = 0 的測地線")

print("\n" + "=" * 70)
print("7. 與牛頓引力的對應")
print("=" * 70)

print("\n弱場近似 (r >> r_s):")
print("g_tt ≈ -(1 - 2M/r) = -(1 - 2Φ/c²)")
print("其中 Φ = -GM/r 是牛頓引力位")
print("\n這給出了牛頓引力的修正項，預測了:")
print("• 水星近日點進動: 43\" per century")
print("• 光線偏折: 1.75\" for grazing the Sun")
print("• 重力時間延遲 (Shapiro delay)")

print("\n" + "=" * 70)
print("示範完成!")
print("=" * 70)

print("\n摘要:")
print("• 史瓦西度規描述了球對稱、靜態黑洞的時空幾何")
print("• 這是愛因斯坦場方程式 G_μν = 8πT_μν 在真空 (T_μν=0) 中的精確解")
print("• 它預測了許多已被實驗證實的廣義相對論效應")
print("• 2015 年 LIGO 首次直接探測到黑洞碰撞的引力波")
print("• 2019 年事件視界望遠鏡 (EHT) 拍攝到首張黑洞照片")