# -*- coding: utf-8 -*-
"""vcalculus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7uQwhd_uA9ByR4KnVlpvD2qPB6P5fjF
"""

"""
SymPy 向量微積分 (sympy.vector) 套件示範
包括梯度、散度、旋度、拉普拉斯算子等
"""

from sympy import symbols, sin, cos, sqrt, simplify, pi, Symbol, exp
from sympy.vector import CoordSys3D, gradient, divergence, curl, laplacian
from sympy.vector import Del, Vector
import sympy.vector as sv

print("=" * 70)
print("SymPy 向量微積分套件 (sympy.vector)")
print("=" * 70)

print("\n" + "=" * 70)
print("1. 建立座標系統")
print("=" * 70)

# 建立笛卡爾座標系統
N = CoordSys3D('N')

# 基底向量
print(f"\n基底向量:")
print(f"  i = {N.i}")
print(f"  j = {N.j}")
print(f"  k = {N.k}")

# 座標變數
print(f"\n座標變數:")
print(f"  x = {N.x}")
print(f"  y = {N.y}")
print(f"  z = {N.z}")

# 原點
print(f"\n原點: {N.origin}")

print("\n" + "=" * 70)
print("2. 向量的定義與運算")
print("=" * 70)

# 定義向量
v1 = 3*N.i + 4*N.j + 5*N.k
v2 = N.x*N.i + N.y*N.j + N.z*N.k  # 位置向量

print(f"\n向量 v1 = {v1}")
print(f"向量 v2 = {v2}")

# 向量運算
v_sum = v1 + N.i
v_cross = v1.cross(v2)
v_dot = v1.dot(v2)
v_magnitude = v1.magnitude()

print(f"\nv1 + i = {v_sum}")
print(f"v1 × v2 = {v_cross}")
print(f"v1 · v2 = {v_dot}")
print(f"|v1| = {v_magnitude}")

print("\n" + "=" * 70)
print("3. 梯度 (Gradient) - ∇f")
print("=" * 70)

print("\n梯度將純量場轉換為向量場")
print("∇f = (∂f/∂x, ∂f/∂y, ∂f/∂z)")

# 定義純量場
f1 = N.x**2 + N.y**2 + N.z**2
print(f"\n純量場 f = {f1}")

# 計算梯度
grad_f1 = gradient(f1, N)
print(f"梯度 ∇f = {grad_f1}")
print(f"展開: ∇f = 2x i + 2y j + 2z k")

print("\n物理意義:")
print("• 梯度指向函數增長最快的方向")
print("• 梯度的大小是變化率")
print("• 重力場: F = -∇Φ (位勢的負梯度)")

# 另一個例子
f2 = N.x*N.y + N.y*N.z + N.z*N.x
print(f"\n純量場 g = {f2}")
grad_f2 = gradient(f2, N)
print(f"梯度 ∇g = {grad_f2}")

# 溫度場例子
f3 = exp(-(N.x**2 + N.y**2 + N.z**2))
print(f"\n溫度場 T = exp(-(x²+y²+z²))")
grad_f3 = gradient(f3, N)
print(f"梯度 ∇T = {grad_f3}")
print("這指向溫度增加的方向(向中心)")

print("\n" + "=" * 70)
print("4. 散度 (Divergence) - ∇·F")
print("=" * 70)

print("\n散度測量向量場的「源」或「匯」")
print("∇·F = ∂Fx/∂x + ∂Fy/∂y + ∂Fz/∂z")

# 定義向量場
F1 = N.x*N.i + N.y*N.j + N.z*N.k
print(f"\n向量場 F1 = {F1}")

# 計算散度
div_F1 = divergence(F1, N)
print(f"散度 ∇·F1 = {div_F1}")

print("\n物理意義:")
print("• div > 0: 源(source) - 流體從此點流出")
print("• div < 0: 匯(sink) - 流體流入此點")
print("• div = 0: 無源場(solenoidal) - 流體不可壓縮")

# 徑向場
F2 = N.x*N.i + N.y*N.j + N.z*N.k
print(f"\n徑向向量場 F2 = x i + y j + z k")
div_F2 = divergence(F2, N)
print(f"散度 ∇·F2 = {div_F2}")
print("常數散度 = 3 表示均勻的源")

# 無源場
F3 = N.y*N.i - N.x*N.j
print(f"\n旋轉向量場 F3 = y i - x j")
div_F3 = divergence(F3, N)
print(f"散度 ∇·F3 = {div_F3}")
print("散度為 0 - 這是無源場(不可壓縮流)")

# 電場例子
print("\n電場例子:")
print("點電荷的電場 E = q·r/r³")
r_vec = N.x*N.i + N.y*N.j + N.z*N.k
r_mag_sq = N.x**2 + N.y**2 + N.z**2
# 簡化的電場(避免奇點)
E_field = r_vec / (r_mag_sq + 1)  # 加1避免奇點
div_E = divergence(E_field, N)
print(f"E = (x i + y j + z k)/(x²+y²+z²+1)")
print(f"∇·E = {simplify(div_E)}")

print("\n" + "=" * 70)
print("5. 旋度 (Curl) - ∇×F")
print("=" * 70)

print("\n旋度測量向量場的「旋轉」")
print("∇×F = |  i    j    k  |")
print("      | ∂/∂x ∂/∂y ∂/∂z|")
print("      | Fx   Fy   Fz  |")

# 旋轉向量場
F4 = -N.y*N.i + N.x*N.j
print(f"\n向量場 F4 = {F4}")

# 計算旋度
curl_F4 = curl(F4, N)
print(f"旋度 ∇×F4 = {curl_F4}")

print("\n物理意義:")
print("• curl ≠ 0: 有旋場 - 流體在旋轉")
print("• curl = 0: 無旋場(irrotational) - 可以寫成位勢的梯度")
print("• 磁場總是無源的: ∇·B = 0")

# 無旋場(梯度場)
F5 = N.x*N.i + N.y*N.j + N.z*N.k
print(f"\n徑向場 F5 = {F5}")
curl_F5 = curl(F5, N)
print(f"旋度 ∇×F5 = {curl_F5}")
print("旋度為 0 - 這是保守力場(可以定義位勢)")

# 磁場例子
print("\n磁場例子(z方向均勻場):")
B_field = N.z*N.k
curl_B = curl(B_field, N)
print(f"B = z k")
print(f"∇×B = {curl_B}")

# 更複雜的例子
F6 = N.y*N.z*N.i + N.x*N.z*N.j + N.x*N.y*N.k
print(f"\n向量場 F6 = yz i + xz j + xy k")
curl_F6 = curl(F6, N)
print(f"旋度 ∇×F6 = {curl_F6}")

print("\n" + "=" * 70)
print("6. 拉普拉斯算子 (Laplacian) - ∇²f = ∇·∇f")
print("=" * 70)

print("\n拉普拉斯算子 = 梯度的散度")
print("∇²f = ∂²f/∂x² + ∂²f/∂y² + ∂²f/∂z²")

# 定義純量場
f4 = N.x**2 + N.y**2 + N.z**2
print(f"\n純量場 f = {f4}")

# 計算拉普拉斯 (不需要第二個參數)
lap_f4 = laplacian(f4)
print(f"拉普拉斯 ∇²f = {lap_f4}")

print("\n重要方程:")
print("• 拉普拉斯方程: ∇²φ = 0 (調和函數)")
print("• 泊松方程: ∇²φ = ρ (靜電學)")
print("• 熱方程: ∂T/∂t = α∇²T")
print("• 波動方程: ∂²u/∂t² = c²∇²u")
print("• 薛丁格方程: iℏ∂ψ/∂t = -ℏ²/2m ∇²ψ + Vψ")

# 調和函數例子
f5 = N.x**2 - N.y**2
print(f"\n函數 h = x² - y²")
lap_f5 = laplacian(f5)
print(f"∇²h = {lap_f5}")
print("這不是調和函數")

# 真正的調和函數
f6 = N.x**3 - 3*N.x*N.y**2
print(f"\n函數 h = x³ - 3xy²")
lap_f6 = laplacian(f6)
print(f"∇²h = {lap_f6}")
print("這是調和函數! ∇²h = 0")

print("\n" + "=" * 70)
print("7. 向量恆等式驗證")
print("=" * 70)

print("\n驗證一些重要的向量恆等式:")

# ∇×(∇f) = 0 (梯度的旋度為零)
print("\n(1) ∇×(∇f) = 0 (梯度無旋)")
f_test = N.x**2*N.y + N.z**3
grad_f = gradient(f_test, N)
curl_grad_f = curl(grad_f, N)
print(f"f = {f_test}")
print(f"∇f = {grad_f}")
print(f"∇×(∇f) = {curl_grad_f}")
print("✓ 梯度的旋度總是零")

# ∇·(∇×F) = 0 (旋度的散度為零)
print("\n(2) ∇·(∇×F) = 0 (旋度無源)")
F_test = N.x*N.y*N.i + N.y*N.z*N.j + N.z*N.x*N.k
curl_F = curl(F_test, N)
div_curl_F = divergence(curl_F, N)
print(f"F = {F_test}")
print(f"∇×F = {curl_F}")
print(f"∇·(∇×F) = {div_curl_F}")
print("✓ 旋度的散度總是零")

# ∇²f = ∇·(∇f) (拉普拉斯定義)
print("\n(3) ∇²f = ∇·(∇f)")
f_test2 = N.x**2 + N.y**2
grad_f2 = gradient(f_test2, N)
div_grad_f2 = divergence(grad_f2, N)
lap_f2 = laplacian(f_test2)
print(f"f = {f_test2}")
print(f"∇·(∇f) = {div_grad_f2}")
print(f"∇²f = {lap_f2}")
print(f"相等: {div_grad_f2 == lap_f2} ✓")

print("\n" + "=" * 70)
print("8. 柱座標系統")
print("=" * 70)

# 柱座標說明
print(f"\n柱座標系統: (r, θ, z)")
print("變換關係:")
print("  x = r cos(θ)")
print("  y = r sin(θ)")
print("  z = z")

print("\n柱座標中的梯度、散度、旋度:")
print("梯度: ∇f = ∂f/∂r e_r + (1/r)∂f/∂θ e_θ + ∂f/∂z e_z")
print("散度: ∇·F = (1/r)∂(rF_r)/∂r + (1/r)∂F_θ/∂θ + ∂F_z/∂z")
print("旋度: ∇×F 的形式也更複雜")

print("\n在 sympy.vector 中使用柱座標:")
print("需要在笛卡爾座標中定義,然後轉換")

# 示範柱座標的向量場
r_expr = sqrt(N.x**2 + N.y**2)
F_radial = (N.x*N.i + N.y*N.j) / r_expr  # 單位徑向向量
print(f"\n徑向單位向量場(笛卡爾表示):")
print(f"F = (x i + y j)/√(x²+y²)")

# 計算散度
div_radial = divergence(F_radial, N)
print(f"散度 ∇·F = {simplify(div_radial)}")

print("\n" + "=" * 70)
print("9. 球座標系統")
print("=" * 70)

print(f"\n球座標系統: (r, θ, φ)")
print("變換關係:")
print("  x = r sin(θ) cos(φ)")
print("  y = r sin(θ) sin(φ)")
print("  z = r cos(θ)")

print("\n球座標中的梯度:")
print("∇f = ∂f/∂r e_r + (1/r)∂f/∂θ e_θ + (1/(r sinθ))∂f/∂φ e_φ")

print("\n球座標中的拉普拉斯算子:")
print("∇² = 1/r² ∂/∂r(r² ∂/∂r) + 1/(r²sinθ) ∂/∂θ(sinθ ∂/∂θ)")
print("     + 1/(r²sin²θ) ∂²/∂φ²")

print("\n常見的球對稱場:")
# 1/r 位勢
r_sph = sqrt(N.x**2 + N.y**2 + N.z**2)
phi_sph = 1/r_sph
print(f"\n萬有引力/靜電位勢: φ = 1/r")
grad_phi = gradient(phi_sph, N)
print(f"∇φ = {grad_phi}")
print("這給出 -r̂/r² 的形式")

# 電場
E_coulomb = -grad_phi
print(f"\n庫倫電場: E = -∇φ = r̂/r²")

print("\n" + "=" * 70)
print("10. 物理應用實例")
print("=" * 70)

print("\n(1) 電磁學 - Maxwell 方程")
print("─" * 50)
print("∇·E = ρ/ε₀        (Gauss 定律)")
print("∇·B = 0           (無磁單極)")
print("∇×E = -∂B/∂t      (Faraday 定律)")
print("∇×B = μ₀J + μ₀ε₀∂E/∂t  (Ampère-Maxwell 定律)")

print("\n(2) 流體力學 - Navier-Stokes 方程")
print("─" * 50)
print("連續性方程: ∂ρ/∂t + ∇·(ρv) = 0")
print("動量方程: ρ(∂v/∂t + v·∇v) = -∇p + μ∇²v + f")

print("\n(3) 熱傳導")
print("─" * 50)
print("∂T/∂t = α∇²T")
print("其中 α 是熱擴散係數")

print("\n(4) 量子力學 - 薛丁格方程")
print("─" * 50)
print("iℏ ∂ψ/∂t = -ℏ²/2m ∇²ψ + V(r)ψ")

print("\n(5) 廣義相對論 - 測地線")
print("─" * 50)
print("雖然不直接用這些算子,但概念類似")
print("協變導數 ∇_μ 推廣了普通導數")

print("\n" + "=" * 70)
print("11. Del 算子的使用")
print("=" * 70)

print("\nDel 算子 ∇ 是一個向量算子:")
print("∇ = (∂/∂x, ∂/∂y, ∂/∂z)")

# 創建 Del 算子
delop = Del()

print("\nDel 算子可以:")
print("• 作用在純量場上: ∇f (梯度)")
print("• 與向量場點乘: ∇·F (散度)")
print("• 與向量場叉乘: ∇×F (旋度)")
print("• 作用兩次: ∇·∇f = ∇²f (拉普拉斯)")

# 使用 Del 計算
f_del = N.x**2 + N.y**2
F_del = N.x*N.i + N.y*N.j

grad_del = gradient(f_del, N)
div_del = divergence(F_del, N)
curl_del = curl(F_del, N)

print(f"\n使用 Del 的計算:")
print(f"f = {f_del}")
print(f"∇f = {grad_del}")
print(f"F = {F_del}")
print(f"∇·F = {div_del}")
print(f"∇×F = {curl_del}")

print("\n" + "=" * 70)
print("示範完成!")
print("=" * 70)

print("\n摘要:")
print("sympy.vector 提供了完整的向量微積分功能:")
print("✓ 3D 向量和座標系統")
print("✓ 梯度 (gradient)")
print("✓ 散度 (divergence)")
print("✓ 旋度 (curl)")
print("✓ 拉普拉斯算子 (laplacian)")
print("✓ 笛卡爾、柱座標、球座標支援")
print("✓ 向量恆等式驗證")
print("✓ 物理應用")

print("\n適用於:")
print("• 電磁學")
print("• 流體力學")
print("• 熱力學")
print("• 量子力學")
print("• 工程計算")
print("• 物理模擬")