# -*- coding: utf-8 -*-
"""flrw.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OeLKMw6lH408CmtmLm4CZ2hmiXS4P9Lq
"""

"""
FLRW (Friedmann-Lemaître-Robertson-Walker) 宇宙模型
描述均勻、各向同性的膨脹宇宙
"""

from sympy import symbols, sin, cos, sqrt, simplify, pi, Symbol, sinh, cosh, Function
from sympy.diffgeom import Manifold, Patch, CoordSystem, TensorProduct
from sympy.diffgeom import metric_to_Christoffel_2nd, metric_to_Ricci_components
from sympy import diff, Rational

print("=" * 70)
print("FLRW 宇宙模型 (Friedmann-Lemaître-Robertson-Walker)")
print("現代宇宙學的標準模型 - 描述均勻、各向同性的膨脹宇宙")
print("=" * 70)

print("\n" + "=" * 70)
print("1. 建立 4 維 FLRW 時空")
print("=" * 70)

# 建立 4 維時空流形
spacetime = Manifold('M', 4)
patch = Patch('P', spacetime)

# 定義宇宙學座標 (t, r, theta, phi)
# t: 宇宙時間(共動時間)
# r: 共動徑向座標
# theta, phi: 角座標
t_sym = Symbol('t', positive=True, real=True)  # 宇宙時間
r_sym = Symbol('r', positive=True, real=True)  # 共動徑向座標
theta_sym = Symbol('theta', real=True)  # 極角
phi_sym = Symbol('phi', real=True)  # 方位角

flrw = CoordSystem('flrw', patch, [t_sym, r_sym, theta_sym, phi_sym])

# 取得座標函數
t, r, theta, phi = flrw.coord_functions()

# 取得基底 1-形式
dt, dr, dtheta, dphi = flrw.base_oneforms()

# 取得基底向量
e_t, e_r, e_theta, e_phi = flrw.base_vectors()

print(f"宇宙學座標: (t, r, θ, φ)")
print(f"t = {t} (宇宙時間/共動時間)")
print(f"r = {r} (共動徑向座標)")
print(f"θ = {theta} (極角)")
print(f"φ = {phi} (方位角)")

print("\n" + "=" * 70)
print("2. FLRW 度規張量")
print("=" * 70)

# 尺度因子 a(t) - 描述宇宙的膨脹
# 使用符號而非座標函數來定義
t_var = Symbol('t', positive=True, real=True)  # 時間變數
a = Function('a')(t_var)  # 尺度因子是時間的函數
print(f"\n尺度因子: a(t) = {a}")
print("a(t) 描述宇宙的大小如何隨時間變化")

# 曲率參數 k
# k = +1: 正曲率(閉合宇宙,球面幾何)
# k = 0:  零曲率(平坦宇宙,歐幾里得幾何)
# k = -1: 負曲率(開放宇宙,雙曲幾何)
k = Symbol('k', real=True)
print(f"\n曲率參數: k = {k}")
print("k = +1: 閉合宇宙 (正曲率)")
print("k =  0: 平坦宇宙 (零曲率)")
print("k = -1: 開放宇宙 (負曲率)")

# FLRW 度規分量
g_tt = -1  # 時間分量
g_rr = a**2 / (1 - k*r**2)  # 徑向分量
g_thetatheta = a**2 * r**2  # 極角分量
g_phiphi = a**2 * r**2 * sin(theta)**2  # 方位角分量

print("\nFLRW 度規的非零分量:")
print(f"g_tt = {g_tt}")
print(f"g_rr = {g_rr}")
print(f"g_θθ = {g_thetatheta}")
print(f"g_φφ = {g_phiphi}")

# 構造度規張量
metric = (g_tt * TensorProduct(dt, dt) +
          g_rr * TensorProduct(dr, dr) +
          g_thetatheta * TensorProduct(dtheta, dtheta) +
          g_phiphi * TensorProduct(dphi, dphi))

print("\n完整的 FLRW 線元:")
print("ds² = -dt² + a²(t)[dr²/(1-kr²) + r²dθ² + r²sin²(θ)dφ²]")

print("\n物理意義:")
print("• 時間分量: -dt² 表示時間流逝")
print("• 空間分量: a²(t)×空間度規")
print("• 尺度因子 a(t) 使整個空間隨時間膨脹或收縮")
print("• 共動觀察者: 隨宇宙膨脹一起運動的觀察者 (r,θ,φ 不變)")

print("\n" + "=" * 70)
print("3. 哈伯定律與宇宙膨脹")
print("=" * 70)

# 哈伯參數 H(t) = ȧ/a
adot = diff(a, t_var)  # 對時間變數求導
H = adot / a
print(f"\n哈伯參數: H(t) = ȧ/a")
print(f"其中 ȧ = da/dt = {adot}")
print("描述宇宙膨脹的速率")

# 現在的哈伯常數
H0 = Symbol('H_0', positive=True, real=True)
print(f"\n現今的哈伯常數: H₀ ≈ 70 km/s/Mpc")
print("(觀測值: 67-74 km/s/Mpc,存在一些爭議)")

print("\n哈伯定律:")
print("v = H₀ × d")
print("其中 v 是退行速度, d 是距離")

print("\n物理距離與共動距離的關係:")
print("物理距離 d(t) = a(t) × r")
print("其中 r 是共動座標(標籤座標)")

print("\n退行速度:")
print("v = ḋ = ȧ(t) × r = H(t) × d(t)")
print("這就是哈伯定律!")

print("\n例子:")
print("距離 100 Mpc 的星系:")
print("  退行速度 v ≈ 70 km/s/Mpc × 100 Mpc = 7000 km/s")
print("距離 1000 Mpc 的星系:")
print("  退行速度 v ≈ 70000 km/s ≈ 0.23c")

print("\n重要注意:")
print("• 這不是星系在空間中的運動")
print("• 而是空間本身在膨脹!")
print("• 星系保持共動座標 r 不變")

print("\n" + "=" * 70)
print("4. 紅移 (Redshift)")
print("=" * 70)

# 宇宙學紅移
z = Symbol('z', positive=True, real=True)
a_now = Symbol('a_0', positive=True, real=True)
a_then = Symbol('a_e', positive=True, real=True)

print("\n紅移定義:")
print("1 + z = λ_觀測 / λ_發射 = a(觀測時) / a(發射時)")
print("1 + z = a₀ / a_e")

print("\n物理意義:")
print("• 光子的波長隨宇宙膨脹而拉伸")
print("• z = 0: 現在(無紅移)")
print("• z = 1: 宇宙大小是現在的 1/2")
print("• z = 2: 宇宙大小是現在的 1/3")
print("• z = 1089: 宇宙微波背景輻射的紅移")

print("\n觀測例子:")
print("z ≈ 0.1: 附近的星系 (~400 Mpc)")
print("z ≈ 1: 遙遠的星系 (~8000 Mpc)")
print("z ≈ 2-3: 類星體")
print("z ≈ 7-10: 最早期的星系")
print("z ≈ 1089: 宇宙微波背景輻射 (CMB)")

print("\n" + "=" * 70)
print("5. 弗里德曼方程 (Friedmann Equations)")
print("=" * 70)

print("\n這是 FLRW 宇宙的運動方程,來自愛因斯坦場方程式")

# 能量密度和壓力
rho = Symbol('rho', positive=True, real=True)  # 能量密度
p = Symbol('p', real=True)  # 壓力
G = Symbol('G', positive=True, real=True)  # 引力常數

print("\n第一弗里德曼方程 (能量方程):")
print("(ȧ/a)² = (8πG/3)ρ - k/a²")
print("H² = (8πG/3)ρ - k/a²")

print("\n第二弗里德曼方程 (加速度方程):")
print("ä/a = -(4πG/3)(ρ + 3p)")

print("\n連續性方程 (能量守恆):")
print("ρ̇ + 3(ȧ/a)(ρ + p) = 0")

print("\n物理意義:")
print("• 第一方程: 膨脹率取決於能量密度和曲率")
print("• 第二方程: 加速度取決於能量密度和壓力")
print("• 連續性方程: 能量守恆")

print("\n" + "=" * 70)
print("6. 宇宙的成分")
print("=" * 70)

print("\n現代宇宙學發現宇宙由三種主要成分組成:")

print("\n(1) 物質 (Matter)")
print("    狀態方程: p_m = 0 (無壓)")
print("    密度演化: ρ_m ∝ a⁻³")
print("    包括: 重子物質(~5%) + 暗物質(~27%)")

print("\n(2) 輻射 (Radiation)")
print("    狀態方程: p_r = ρ_r/3")
print("    密度演化: ρ_r ∝ a⁻⁴")
print("    包括: 光子 + 微中子")

print("\n(3) 暗能量 (Dark Energy)")
print("    狀態方程: p_Λ = -ρ_Λ (負壓!)")
print("    密度演化: ρ_Λ = 常數")
print("    占宇宙總能量的 ~68%")

print("\n現今宇宙的組成 (Planck 2018):")
print("• 暗能量: ~68.3%")
print("• 暗物質: ~26.8%")
print("• 重子物質: ~4.9%")
print("• 輻射: ~0.01% (現在可忽略)")

print("\n" + "=" * 70)
print("7. 宇宙的演化歷史")
print("=" * 70)

print("\n不同時期由不同成分主導:")

print("\n(1) 輻射主導時期 (Radiation-dominated era)")
print("    時間: t < 47,000 年")
print("    尺度因子: a(t) ∝ t^(1/2)")
print("    溫度極高,粒子以接近光速運動")

print("\n(2) 物質主導時期 (Matter-dominated era)")
print("    時間: 47,000 年 < t < 100 億年")
print("    尺度因子: a(t) ∝ t^(2/3)")
print("    星系和結構形成時期")

print("\n(3) 暗能量主導時期 (Dark energy-dominated era)")
print("    時間: t > 100 億年 (現在!)")
print("    尺度因子: a(t) ∝ e^(Ht) (指數膨脹)")
print("    宇宙加速膨脹")

print("\n" + "=" * 70)
print("8. 臨界密度與密度參數")
print("=" * 70)

print("\n臨界密度 ρ_c:")
print("ρ_c = 3H²/(8πG)")
print("這是使宇宙平坦 (k=0) 所需的密度")

print("\n密度參數 Ω:")
print("Ω = ρ/ρ_c")
print("Ω_m: 物質密度參數 ≈ 0.315")
print("Ω_Λ: 暗能量密度參數 ≈ 0.685")
print("Ω_k: 曲率項 = -k/(aH)²")

print("\n弗里德曼方程可改寫為:")
print("Ω_m + Ω_Λ + Ω_k = 1")

print("\n觀測結果:")
print("Ω_total ≈ 1.000 ± 0.002")
print("這強烈暗示我們的宇宙是平坦的 (k = 0)!")

print("\n" + "=" * 70)
print("9. 計算 Christoffel 符號")
print("=" * 70)

print("\n計算中... (這需要一些時間)")

# 為了簡化計算,我們考慮 k=0 的平坦宇宙
print("\n簡化為平坦宇宙 (k = 0) 來演示計算:")

# 重新定義度規(k=0)
metric_flat = (g_tt * TensorProduct(dt, dt) +
               a**2 * TensorProduct(dr, dr) +
               a**2 * r**2 * TensorProduct(dtheta, dtheta) +
               a**2 * r**2 * sin(theta)**2 * TensorProduct(dphi, dphi))

christoffel = metric_to_Christoffel_2nd(metric_flat)

print("\n一些重要的非零 Christoffel 符號:")

# 顯示符號形式(因為實際計算會很複雜)
print(f"\n與膨脹相關的項:")
print(f"Γ^t_rr = -a·ȧ/(1-kr²)")
print(f"Γ^r_tr = Γ^r_rt = ȧ/a = H(t)")
print(f"Γ^t_θθ = -a·ȧ·r²")
print(f"Γ^θ_tθ = Γ^θ_θt = ȧ/a = H(t)")
print(f"Γ^t_φφ = -a·ȧ·r²sin²(θ)")
print(f"Γ^φ_tφ = Γ^φ_φt = ȧ/a = H(t)")

print("\n空間部分(類似球座標):")
print(f"Γ^r_θθ = -r(1-kr²)")
print(f"Γ^r_φφ = -r(1-kr²)sin²(θ)")
print(f"Γ^θ_rθ = 1/r")
print(f"Γ^θ_φφ = -sin(θ)cos(θ)")
print(f"Γ^φ_rφ = 1/r")
print(f"Γ^φ_θφ = cot(θ)")

print("\n曲率相關的項:")
print(f"Γ^r_rr = kr/(1-kr²)")

print("\n物理意義:")
print("• Γ^r_tr = H 項來自宇宙膨脹")
print("• 這些項使共動粒子保持共動座標不變")
print("• 時間導數項反映空間本身的膨脹")

print("\n" + "=" * 70)
print("10. 宇宙視界 (Cosmological Horizons)")
print("=" * 70)

print("\n(1) 粒子視界 (Particle Horizon)")
print("    光從大爆炸以來能傳播的最大距離")
print("    定義我們能觀測的宇宙範圍")
print("    現在約 460 億光年")

print("\n(2) 哈伯視界 (Hubble Horizon)")
print("    d_H = c/H₀")
print("    退行速度等於光速的距離")
print("    約 140 億光年")

print("\n(3) 事件視界 (Event Horizon)")
print("    在暗能量主導的宇宙中存在")
print("    我們將永遠無法觀測到的區域")

print("\n可觀測宇宙:")
print("• 半徑: ~460 億光年")
print("• 包含: ~2 兆個星系")
print("• 但宇宙可能無限大!")

print("\n" + "=" * 70)
print("11. 宇宙微波背景輻射 (CMB)")
print("=" * 70)

print("\n起源:")
print("• 宇宙年齡 ~380,000 年")
print("• 溫度 ~3000 K")
print("• 電子和質子結合成氫原子(復合)")
print("• 宇宙從不透明變為透明")

print("\n觀測:")
print("• 發現: 1964 年 (Penzias & Wilson)")
print("• 現今溫度: 2.725 K")
print("• 紅移: z ≈ 1089")
print("• 各向同性精度: ~10⁻⁵")

print("\n重要性:")
print("• 確認大爆炸理論")
print("• 精確測量宇宙學參數")
print("• 提供早期宇宙的快照")

print("\n" + "=" * 70)
print("12. 宇宙的未來")
print("=" * 70)

print("\n基於 Ω_Λ > 0 (暗能量主導):")

print("\n短期 (~100 億年):")
print("• 繼續加速膨脹")
print("• 星系形成減少")
print("• 更多星系超出視界")

print("\n長期 (~10¹² 年):")
print("• 恆星耗盡燃料")
print("• 星系變暗")
print("• 宇宙變冷、變暗")

print("\n極長期 (~10¹⁰⁰ 年以上):")
print("• 可能的熱寂 (Heat Death)")
print("• 黑洞蒸發 (霍金輻射)")
print("• 大撕裂? (如果暗能量增強)")

print("\n" + "=" * 70)
print("13. 觀測證據總結")
print("=" * 70)

print("\n支持 FLRW 模型的觀測:")
print("✓ 哈伯定律 (1929)")
print("✓ 宇宙微波背景輻射 (1964)")
print("✓ 核合成豐度 (氦、氘等)")
print("✓ 大尺度結構")
print("✓ Ia 型超新星 (宇宙加速膨脹, 1998)")
print("✓ 重子聲學震盪 (BAO)")
print("✓ 引力透鏡")

print("\n重大發現:")
print("• 1998: 發現宇宙加速膨脹 (諾貝爾獎 2011)")
print("• 必須引入暗能量來解釋")
print("• 這是現代物理學最大的謎團之一")

print("\n" + "=" * 70)
print("示範完成!")
print("=" * 70)

print("\n摘要:")
print("• FLRW 度規描述均勻、各向同性的宇宙")
print("• 尺度因子 a(t) 描述宇宙如何隨時間膨脹")
print("• 弗里德曼方程決定宇宙的演化")
print("• 觀測表明:宇宙平坦、加速膨脹、由暗能量主導")
print("• 這是現代宇宙學的標準模型 (ΛCDM)")
print("\n未解之謎:")
print("• 暗能量的本質是什麼?")
print("• 暗物質由什麼組成?")
print("• 為什麼宇宙如此平坦?")
print("• 大爆炸之前發生了什麼?")