# -*- coding: utf-8 -*-
"""kerr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QbbPEdz4uQBJCn_6ukuCcjC0j2OQzdZ8
"""

"""
Kerr 度規 (Kerr Metric) 示範
描述旋轉黑洞的時空幾何 - 最一般的黑洞解
"""

from sympy import symbols, sin, cos, sqrt, simplify, pi, Symbol, Function
from sympy.diffgeom import Manifold, Patch, CoordSystem, TensorProduct
from sympy.diffgeom import metric_to_Christoffel_2nd
from sympy import Matrix

print("=" * 70)
print("Kerr 旋轉黑洞度規 (Kerr Metric)")
print("描述旋轉黑洞的時空幾何 - 現實宇宙中黑洞的通用解")
print("=" * 70)

print("\n" + "=" * 70)
print("1. 建立 4 維時空流形")
print("=" * 70)

# 建立 4 維時空流形
spacetime = Manifold('M', 4)
patch = Patch('P', spacetime)

# 定義 Boyer-Lindquist 座標 (t, r, theta, phi)
# 這是 Kerr 度規最常用的座標系統
t_sym = Symbol('t', real=True)  # 時間座標
r_sym = Symbol('r', positive=True, real=True)  # 徑向座標
theta_sym = Symbol('theta', real=True)  # 極角
phi_sym = Symbol('phi', real=True)  # 方位角

kerr = CoordSystem('kerr', patch, [t_sym, r_sym, theta_sym, phi_sym])

# 取得座標函數
t, r, theta, phi = kerr.coord_functions()

# 取得基底 1-形式
dt, dr, dtheta, dphi = kerr.base_oneforms()

# 取得基底向量
e_t, e_r, e_theta, e_phi = kerr.base_vectors()

print(f"Boyer-Lindquist 座標: (t, r, θ, φ)")
print(f"t = {t} (時間座標)")
print(f"r = {r} (徑向座標)")
print(f"θ = {theta} (極角, 從旋轉軸測量)")
print(f"φ = {phi} (方位角)")

print("\n" + "=" * 70)
print("2. Kerr 度規的參數")
print("=" * 70)

# 質量參數
M = Symbol('M', positive=True, real=True)  # 黑洞質量
print(f"\n質量參數: M = {M}")

# 角動量參數
a = Symbol('a', real=True)  # 單位質量的角動量 (J/M)
print(f"角動量參數: a = J/M = {a}")
print("a 的範圍: 0 ≤ |a| ≤ M")
print("  a = 0: 史瓦西黑洞 (不旋轉)")
print("  0 < |a| < M: 慢旋轉黑洞")
print("  |a| = M: 極端 Kerr 黑洞 (最大旋轉)")
print("  |a| > M: 裸奇異點 (不物理,違反宇宙監督假設)")

# 輔助函數
# Σ = r² + a²cos²(θ)
Sigma = r**2 + a**2 * cos(theta)**2
print(f"\n輔助函數 Σ(r,θ) = r² + a²cos²(θ) = {Sigma}")

# Δ = r² - 2Mr + a²
Delta = r**2 - 2*M*r + a**2
print(f"輔助函數 Δ(r) = r² - 2Mr + a² = {Delta}")

print("\n" + "=" * 70)
print("3. Kerr 度規張量")
print("=" * 70)

# Kerr 度規的非對角形式
# g_tt
g_tt = -(1 - 2*M*r/Sigma)
print(f"\ng_tt = {g_tt}")

# g_tφ (交叉項!)
g_tphi = -2*M*r*a*sin(theta)**2 / Sigma
print(f"g_tφ = {g_tphi}")

# g_rr
g_rr = Sigma / Delta
print(f"g_rr = {g_rr}")

# g_θθ
g_thetatheta = Sigma
print(f"g_θθ = {g_thetatheta}")

# g_φφ
g_phiphi = (r**2 + a**2 + 2*M*r*a**2*sin(theta)**2/Sigma) * sin(theta)**2
print(f"g_φφ = {g_phiphi}")

# 構造度規張量
metric = (g_tt * TensorProduct(dt, dt) +
          g_tphi * (TensorProduct(dt, dphi) + TensorProduct(dphi, dt)) +
          g_rr * TensorProduct(dr, dr) +
          g_thetatheta * TensorProduct(dtheta, dtheta) +
          g_phiphi * TensorProduct(dphi, dphi))

print("\n完整的 Kerr 線元:")
print("ds² = -(1-2Mr/Σ)dt² - (4Mra sin²θ/Σ)dt dφ")
print("      + (Σ/Δ)dr² + Σdθ²")
print("      + [(r²+a²)² - a²Δsin²θ]/Σ · sin²θ dφ²")

print("\n關鍵特徵:")
print("• g_tφ ≠ 0: 時空被拖曳 (參考系拖曳效應)")
print("• 軸對稱性: 不依賴於 φ")
print("• 穩態: 不依賴於 t")
print("• 當 a → 0 時,退化為史瓦西度規")

print("\n" + "=" * 70)
print("4. 事件視界與能層")
print("=" * 70)

# 事件視界: Δ = 0 的解
print("\n事件視界位置 (Δ = 0):")
print("r² - 2Mr + a² = 0")

# 外視界
r_plus = M + sqrt(M**2 - a**2)
print(f"\n外視界: r₊ = M + √(M² - a²) = {r_plus}")

# 內視界
r_minus = M - sqrt(M**2 - a**2)
print(f"內視界: r₋ = M - √(M² - a²) = {r_minus}")

print("\n特殊情況:")
print("• a = 0 (史瓦西): r₊ = 2M, r₋ = 0")
print("• a = M (極端 Kerr): r₊ = r₋ = M")

# 能層 (Ergosphere)
print("\n能層 (Ergosphere):")
print("g_tt = 0 的表面")
r_ergo = M + sqrt(M**2 - a**2*cos(theta)**2)
print(f"r_ergo = M + √(M² - a²cos²θ)")

print("\n能層的範圍:")
print("• 在極點 (θ=0,π): r_ergo = r₊ (與視界重合)")
print("• 在赤道 (θ=π/2): r_ergo = 2M (比視界大)")
print("• 能層區域: r₊ < r < r_ergo")

print("\n能層的物理意義:")
print("• 在能層內,所有物體都必須旋轉")
print("• 無法保持靜止 (沒有類時 Killing 向量)")
print("• 但仍可逃離黑洞 (在視界外)")

print("\n" + "=" * 70)
print("5. 參考系拖曳 (Frame Dragging)")
print("=" * 70)

print("\n角速度 ω(r,θ):")
omega = -g_tphi / g_phiphi
omega_simplified = 2*M*r*a / ((r**2 + a**2)**2 - a**2*Delta*sin(theta)**2)
print("ω = -g_tφ/g_φφ")
print("這是時空被拖曳的角速度")

print("\n物理意義:")
print("• 零角動量觀察者 (ZAMO) 必須以 ω 旋轉")
print("• 時空本身被旋轉黑洞拖曳")
print("• 越靠近黑洞,拖曳效應越強")

print("\n在視界上的角速度:")
omega_horizon = a / (2*M*r_plus)
print(f"ω_H = a/(2Mr₊)")
print("這是視界的旋轉頻率")

print("\n實驗驗證:")
print("• Gravity Probe B (2004-2005)")
print("• LIGO/Virgo 引力波觀測")
print("• 地球的參考系拖曳: ~0.000,000,01 度/年")

print("\n" + "=" * 70)
print("6. 彭羅斯過程 (Penrose Process)")
print("=" * 70)

print("\n能層中的能量提取:")
print("1. 粒子進入能層區域")
print("2. 粒子分裂為兩部分")
print("3. 一部分落入黑洞 (負能量)")
print("4. 另一部分逃出 (能量增加!)")

print("\n最大提取效率:")
eta_max = 1 - sqrt(1 - a**2/(2*M**2))
print("η_max = 1 - √(1 - a²/2M²)")
print("對於極端 Kerr 黑洞 (a=M): η ≈ 29%")

print("\n比較:")
print("• 核融合效率: ~0.7%")
print("• 物質-反物質湮滅: 100%")
print("• 彭羅斯過程: 最高 29%")

print("\n天體物理應用:")
print("• 類星體的能量來源")
print("• 活動星系核 (AGN)")
print("• γ 射線暴")

print("\n" + "=" * 70)
print("7. 主要軌道")
print("=" * 70)

print("\n(1) 最內層穩定圓軌道 (ISCO)")
print("    粒子能穩定繞行的最內層軌道")

# ISCO 半徑 (赤道面,順行)
print("\n順行軌道 (與黑洞同向旋轉):")
print("r_ISCO = M{3 + Z₂ - √[(3-Z₁)(3+Z₁+2Z₂)]}")
print("其中 Z₁, Z₂ 是 a 的函數")

print("\n特殊情況:")
print("• a = 0 (史瓦西): r_ISCO = 6M")
print("• a = M (極端,順行): r_ISCO = M")
print("• a = M (極端,逆行): r_ISCO = 9M")

print("\n(2) 光子軌道")
print("    光子的圓軌道")
print("    r_photon ~ 3-4M (取決於 a)")

print("\n(3) 測地線類型:")
print("• 類時測地線: 大質量粒子")
print("• 類光測地線: 光子")
print("• 類空測地線: 不物理")

print("\n" + "=" * 70)
print("8. 黑洞陰影")
print("=" * 70)

print("\n光子軌道形成黑洞陰影:")
print("• 視界並不直接可見")
print("• 看到的是光子球的投影")
print("• 陰影大小 ~ 5M (視角)")

print("\n2019 年事件視界望遠鏡 (EHT):")
print("• 拍攝 M87* 黑洞")
print("• 質量: ~6.5×10⁹ M_☉")
print("• 距離: ~55 百萬光年")
print("• 陰影直徑: ~42 微角秒")

print("\n2022 年 EHT:")
print("• 拍攝銀河系中心 Sgr A*")
print("• 質量: ~4×10⁶ M_☉")
print("• 距離: ~26,000 光年")

print("\n從陰影形狀可推斷:")
print("• 黑洞質量 M")
print("• 自旋參數 a")
print("• 傾角 i")

print("\n" + "=" * 70)
print("9. Kerr 與 Schwarzschild 的比較")
print("=" * 70)

print("\n相同點:")
print("✓ 都是愛因斯坦場方程式的精確解")
print("✓ 都是真空解 (外部無物質)")
print("✓ 都有事件視界")
print("✓ 都有奇異點")

print("\n不同點:")
print("Schwarzschild (a=0)     |  Kerr (a≠0)")
print("─" * 60)
print("球對稱                  |  軸對稱")
print("靜態                    |  穩態(非靜態)")
print("無參考系拖曳            |  有參考系拖曳")
print("g_tφ = 0                |  g_tφ ≠ 0")
print("點奇異點                |  環狀奇異點")
print("1 個視界                |  2 個視界 (r₊, r₋)")
print("無能層                  |  有能層")
print("不可提取能量            |  可提取能量 (彭羅斯)")

print("\n" + "=" * 70)
print("10. 環狀奇異點")
print("=" * 70)

print("\n與史瓦西的點奇異點不同:")
print("• Kerr 的奇異點是環狀")
print("• 位於: r=0, θ=π/2 (赤道面)")
print("• 半徑: a (在旋轉軸上)")

print("\n理論上的穿越:")
print("• 可能穿過環而不碰到奇異點")
print("• 進入另一個宇宙區域?")
print("• 時間機器的可能性?")
print("• 但量子效應可能阻止這些")

print("\n現實的限制:")
print("• 內視界不穩定")
print("• 量子效應尚未理解")
print("• 可能需要量子重力理論")

print("\n" + "=" * 70)
print("11. 克爾黑洞的形成")
print("=" * 70)

print("\n恆星塌縮:")
print("• 大質量恆星 (>20-25 M_☉)")
print("• 核心塌縮成黑洞")
print("• 保留恆星的角動量")
print("• 典型 a/M ~ 0.7-0.99")

print("\n黑洞合併:")
print("• 雙黑洞系統")
print("• 螺旋內落")
print("• 發射引力波")
print("• 最終形成旋轉黑洞")
print("• LIGO/Virgo 已觀測多次")

print("\n吸積盤:")
print("• 物質落入黑洞")
print("• 可以加速或減速旋轉")
print("• 長期演化傾向 a → M")

print("\n" + "=" * 70)
print("12. 計算 Christoffel 符號 (符號形式)")
print("=" * 70)

print("\n由於 Kerr 度規的複雜性,Christoffel 符號非常繁瑣")
print("這裡列出幾個重要的類型:")

print("\n時間-方位角混合項 (參考系拖曳):")
print("Γ^φ_tt ≠ 0  (時間演化影響方位角)")
print("Γ^t_φφ ≠ 0  (旋轉影響時間)")
print("這些項體現了時空的旋轉")

print("\n徑向項:")
print("Γ^r_rr ∝ (r-M)/Δ  (與史瓦西類似但有修正)")
print("Γ^t_rr ∝ M(r²-a²cos²θ)/Σ²")

print("\n角度項:")
print("Γ^θ_φφ ∝ sin(θ)cos(θ)  (球座標的典型項)")
print("但還有來自旋轉的額外複雜項")

print("\n完整計算需要計算機代數系統:")
print("• 64 個獨立的 Christoffel 符號")
print("• 每個都是 M, a, r, θ 的複雜函數")
print("• 用於數值相對論和引力波模擬")

print("\n" + "=" * 70)
print("13. 天體物理觀測")
print("=" * 70)

print("\n自旋測量方法:")

print("\n(1) X 射線連續譜擬合")
print("    • 從吸積盤的 X 射線輻射")
print("    • ISCO 位置依賴於 a")

print("\n(2) Fe Kα 譜線")
print("    • 鐵的 X 射線發射線")
print("    • 多普勒和引力紅移")
print("    • 譜線輪廓敏感於 a")

print("\n(3) 類星體的噴流")
print("    • 噴流功率與 a 相關")
print("    • 彭羅斯機制或 BZ 機制")

print("\n(4) 引力波")
print("    • 合併前的軌道進動")
print("    • 併合後的準簡正模")
print("    • 最終黑洞的 a/M")

print("\n觀測到的自旋值:")
print("• 恆星級黑洞: a/M ~ 0-0.99")
print("• 超大質量黑洞: a/M ~ 0.5-0.99")
print("• Cygnus X-1: a/M > 0.95")
print("• M87*: a/M ~ 0.9 ± 0.1")

print("\n" + "=" * 70)
print("14. 理論重要性")
print("=" * 70)

print("\nKerr 定理 (無毛定理):")
print("• 所有穩態黑洞由 3 個參數完全描述:")
print("  1. 質量 M")
print("  2. 電荷 Q")
print("  3. 角動量 J")
print("• 天體物理黑洞: Q ≈ 0 (中性)")
print("• 因此只需 M 和 J (Kerr 解)")

print("\n唯一性定理:")
print("• Kerr 度規是唯一的旋轉真空黑洞解")
print("• 所有天體物理黑洞最終都是 Kerr")

print("\n宇宙監督假設:")
print("• |a| ≤ M (沒有裸奇異點)")
print("• 尚未證明,但廣泛相信")
print("• 如果違反,因果性可能被破壞")

print("\n" + "=" * 70)
print("15. 數值例子")
print("=" * 70)

print("\n太陽質量黑洞 (M = 1 M_☉):")
M_sun_km = 1.477  # 幾何單位的 km
print(f"  幾何質量: M = {M_sun_km:.3f} km")
print(f"  史瓦西半徑: r_s = 2M = {2*M_sun_km:.3f} km")

print("\n極端 Kerr 黑洞 (a = M):")
print(f"  視界: r₊ = M = {M_sun_km:.3f} km")
print(f"  能層(赤道): r_ergo = 2M = {2*M_sun_km:.3f} km")
print(f"  ISCO(順行): r_ISCO = M = {M_sun_km:.3f} km")

print("\n慢旋轉 (a = 0.5M):")
r_plus_val = 1 + sqrt(1 - 0.5**2)
print(f"  視界: r₊ ≈ {r_plus_val:.3f}M = {r_plus_val*M_sun_km:.3f} km")

print("\n銀河系中心黑洞 Sgr A*:")
M_sgr = 4e6  # 太陽質量
print(f"  質量: M ≈ {M_sgr:.1e} M_☉")
print(f"  視界(a=0.9M): r₊ ≈ 0.56M ≈ {0.56*M_sgr*M_sun_km/1e6:.1f} 百萬 km")
print(f"  約 {0.56*M_sgr*M_sun_km/1.496e8:.3f} AU")

print("\n" + "=" * 70)
print("示範完成!")
print("=" * 70)

print("\n摘要:")
print("• Kerr 度規描述旋轉黑洞 - 最一般的黑洞解")
print("• 關鍵特徵: 參考系拖曳、能層、環狀奇異點")
print("• 可以從能層提取能量 (彭羅斯過程)")
print("• 無毛定理: 只需 M 和 a 就能完全描述")
print("• 幾乎所有天體物理黑洞都是 Kerr 黑洞")
print("• EHT 首次直接觀測黑洞陰影")
print("\n歷史:")
print("• 1916: 史瓦西解 (不旋轉)")
print("• 1963: Roy Kerr 發現旋轉黑洞解")
print("• 2015-2019: LIGO/Virgo 探測引力波")
print("• 2019, 2022: EHT 拍攝黑洞照片")