# -*- coding: utf-8 -*-
"""minkowski.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pUrhz_nM_zKan3cZPqjx-TPyfFORTJo8
"""

"""
閔可夫斯基時空 (Minkowski Spacetime) 示範
狹義相對論的數學基礎，展示尺縮、鐘慢等效應
"""

from sympy import symbols, sin, cos, sqrt, simplify, pi, Symbol, sinh, cosh, Matrix
from sympy.diffgeom import Manifold, Patch, CoordSystem, TensorProduct
from sympy.diffgeom import metric_to_Christoffel_2nd

print("=" * 70)
print("閔可夫斯基時空 (Minkowski Spacetime)")
print("狹義相對論的平直時空 - 沒有重力的自由空間")
print("=" * 70)

print("\n" + "=" * 70)
print("1. 建立 4 維閔可夫斯基時空")
print("=" * 70)

# 建立 4 維時空流形
spacetime = Manifold('M', 4)
patch = Patch('P', spacetime)

# 定義慣性座標系統 (t, x, y, z) - 靜止參考系
t_sym = Symbol('t', real=True)  # 時間座標
x_sym = Symbol('x', real=True)  # x 空間座標
y_sym = Symbol('y', real=True)  # y 空間座標
z_sym = Symbol('z', real=True)  # z 空間座標

inertial = CoordSystem('inertial', patch, [t_sym, x_sym, y_sym, z_sym])

# 取得座標函數
t, x, y, z = inertial.coord_functions()

# 取得基底 1-形式
dt, dx, dy, dz = inertial.base_oneforms()

# 取得基底向量
e_t, e_x, e_y, e_z = inertial.base_vectors()

print(f"慣性參考系座標: (t, x, y, z)")
print(f"時間座標: t = {t}")
print(f"空間座標: x = {x}, y = {y}, z = {z}")

print("\n" + "=" * 70)
print("2. 閔可夫斯基度規 (平直時空度規)")
print("=" * 70)

# 使用 (-,+,+,+) 號差約定 (適合粒子物理)
# 也可以用 (+,-,-,-) 號差約定 (適合廣義相對論)

print("\n使用 (-,+,+,+) 號差約定:")
print("g_μν = diag(-1, 1, 1, 1)")

# 度規分量
g_tt = -1  # 時間分量為負
g_xx = 1   # 空間分量為正
g_yy = 1
g_zz = 1

# 構造閔可夫斯基度規
metric = (g_tt * TensorProduct(dt, dt) +
          g_xx * TensorProduct(dx, dx) +
          g_yy * TensorProduct(dy, dy) +
          g_zz * TensorProduct(dz, dz))

print("\n閔可夫斯基線元:")
print("ds² = -dt² + dx² + dy² + dz²")
print("或寫成: ds² = -c²dt² + dx² + dy² + dz² (恢復光速 c)")

print("\n不變間隔的物理意義:")
print("• ds² < 0: 類時間隔 (timelike) - 可以有因果關係")
print("• ds² = 0: 類光間隔 (lightlike/null) - 光子的軌跡")
print("• ds² > 0: 類空間隔 (spacelike) - 無因果關係")

print("\n" + "=" * 70)
print("3. 驗證平直時空 - Christoffel 符號全為零")
print("=" * 70)

# 計算 Christoffel 符號
christoffel = metric_to_Christoffel_2nd(metric)

print("\n檢查所有 Christoffel 符號...")
all_zero = True
for i in range(4):
    for j in range(4):
        for k in range(4):
            if christoffel[i, j, k] != 0:
                print(f"Γ^{i}_{j}{k} = {christoffel[i, j, k]}")
                all_zero = False

if all_zero:
    print("✓ 所有 Christoffel 符號 Γ^μ_αβ = 0")
    print("✓ 這證實了閔可夫斯基時空是平直的 (無曲率)")
    print("✓ 測地線就是直線!")

print("\n" + "=" * 70)
print("4. 洛倫茲變換 (Lorentz Transformation)")
print("=" * 70)

# 定義運動參考系 - 沿 x 軸以速度 v 運動
v = Symbol('v', real=True)  # 速度參數
c = Symbol('c', positive=True, real=True)  # 光速
beta = v/c  # 無量綱速度
gamma = 1/sqrt(1 - beta**2)  # 洛倫茲因子

print(f"\n運動參考系以速度 v 沿 x 軸運動")
print(f"速度參數: β = v/c = {beta}")
print(f"洛倫茲因子: γ = 1/√(1-β²) = {gamma}")

# 洛倫茲變換矩陣
print("\n洛倫茲變換:")
print("t' = γ(t - vx/c²)")
print("x' = γ(x - vt)")
print("y' = y")
print("z' = z")

# 定義運動座標系的符號
t_prime_sym = Symbol('t_prime', real=True)
x_prime_sym = Symbol('x_prime', real=True)
y_prime_sym = Symbol('y_prime', real=True)
z_prime_sym = Symbol('z_prime', real=True)

# 建立座標變換關係
# relations 格式: {(from_sys, to_sys): ((from_coords,), (to_coords_expressions,))}
relations_dict = {
    ('inertial', 'moving'): (
        (t_sym, x_sym, y_sym, z_sym),  # inertial 系的坐標符號
        (
            gamma * (t_prime_sym + beta * x_prime_sym),  # t = γ(t' + vx'/c²)
            gamma * (x_prime_sym + v * t_prime_sym),     # x = γ(x' + vt')
            y_prime_sym,                                  # y = y'
            z_prime_sym                                   # z = z'
        )
    )
}

# 使用 relations 參數創建運動座標系
moving = CoordSystem('moving', patch,
                    [t_prime_sym, x_prime_sym, y_prime_sym, z_prime_sym],
                    relations=relations_dict)

print("\n✓ 洛倫茲變換已建立")

# 驗證變換
print("\n驗證坐標變換:")
t_prime, x_prime, y_prime, z_prime = moving.coord_functions()
print(f"運動系時間坐標: {t_prime}")
print(f"運動系空間坐標: ({x_prime}, {y_prime}, {z_prime})")

# 顯示反變換公式
print("\n反變換 (靜止系 → 運動系):")
print("t' = γ(t - vx/c²)")
print("x' = γ(x - vt)")
print("y' = y")
print("z' = z")

print("\n" + "=" * 70)
print("5. 時間膨脹 (鐘慢效應 - Time Dilation)")
print("=" * 70)

print("\n考慮一個靜止在運動參考系中的時鐘")
print("在運動系中: Δx' = 0, Δt' = τ (固有時)")
print("\n在靜止參考系中觀察這個時鐘:")

# 時間膨脹公式
dt_observed = gamma * t_prime  # 當 dx' = 0
print(f"\nΔt = γΔt' = {gamma} × Δt'")
print(f"Δt = Δt'/√(1-v²/c²)")

print("\n數值例子:")
print("當 v = 0.6c 時:")
v_val = 0.6
gamma_val = 1/sqrt(1 - v_val**2)
print(f"  γ = {gamma_val:.3f}")
print(f"  運動系中過 1 秒,靜止系中觀察到 {gamma_val:.3f} 秒")
print(f"  時間變慢了!")

print("\n當 v = 0.9c 時:")
v_val = 0.9
gamma_val = 1/sqrt(1 - v_val**2)
print(f"  γ = {gamma_val:.3f}")
print(f"  運動系中過 1 秒,靜止系中觀察到 {gamma_val:.3f} 秒")

print("\n當 v = 0.99c 時:")
v_val = 0.99
gamma_val = 1/sqrt(1 - v_val**2)
print(f"  γ = {gamma_val:.3f}")
print(f"  運動系中過 1 秒,靜止系中觀察到 {gamma_val:.3f} 秒")

print("\n實驗驗證:")
print("• μ 子壽命實驗 (1941)")
print("• GPS 衛星需要相對論修正 (每天約 38 微秒)")
print("• 粒子加速器中的高速粒子")

print("\n" + "=" * 70)
print("6. 長度收縮 (尺縮效應 - Length Contraction)")
print("=" * 70)

print("\n考慮一根靜止在運動參考系中的尺")
print("在運動系中的長度: L₀ (固有長度)")
print("尺的兩端坐標: x'₁ 和 x'₂, 長度 L₀ = x'₂ - x'₁")

print("\n在靜止參考系中同時(Δt=0)測量這根尺:")
print("由洛倫茲變換: x' = γ(x - vt)")
print("對於同時事件 (t₁ = t₂):")
print("Δx' = γΔx")
print("因此: L = Δx = Δx'/γ = L₀/γ")

# 長度收縮公式
L_contracted = t_prime / gamma  # L = L₀/γ
print(f"\nL = L₀/γ = L₀√(1-v²/c²)")
print(f"L = L₀ × √(1-v²/c²)")

print("\n數值例子:")
print("一根 1 米的尺在高速運動:")

print("\n當 v = 0.6c 時:")
v_val = 0.6
contraction = sqrt(1 - v_val**2)
print(f"  收縮因子 = {contraction:.3f}")
print(f"  測量長度 = {contraction:.3f} 米")

print("\n當 v = 0.9c 時:")
v_val = 0.9
contraction = sqrt(1 - v_val**2)
print(f"  收縮因子 = {contraction:.3f}")
print(f"  測量長度 = {contraction:.3f} 米")

print("\n當 v = 0.99c 時:")
v_val = 0.99
contraction = sqrt(1 - v_val**2)
print(f"  收縮因子 = {contraction:.3f}")
print(f"  測量長度 = {contraction:.3f} 米")

print("\n重要注意:")
print("• 只有沿運動方向的長度收縮")
print("• 垂直於運動方向的尺寸不變")
print("• 這是真實的物理效應,不是視覺錯覺")

print("\n" + "=" * 70)
print("7. 同時性的相對性 (Relativity of Simultaneity)")
print("=" * 70)

print("\n在靜止系中同時發生的兩個事件 (Δt = 0):")
print("事件 1: (t, x₁, y₁, z₁)")
print("事件 2: (t, x₂, y₂, z₂)")

print("\n在運動系中觀察:")
print("由 t' = γ(t - vx/c²)")
print("Δt' = γ(Δt - vΔx/c²) = -γvΔx/c²")

print("\n結論: Δt' ≠ 0")
print("在靜止系中同時的事件,在運動系中不同時!")
print("同時性是相對的,取決於觀察者的運動狀態")

print("\n數值例子:")
print("兩個相距 1 光秒的同時事件 (Δx = 3×10⁸ m, Δt = 0)")
print("\n對於以 v = 0.6c 運動的觀察者:")
v_val = 0.6
gamma_val = 1/sqrt(1 - v_val**2)
dt_prime = -gamma_val * v_val * 1  # Δx = 1 光秒
print(f"  時間差 Δt' = {dt_prime:.3f} 秒")
print(f"  相差約 {abs(dt_prime):.3f} 秒!")

print("\n" + "=" * 70)
print("8. 速度加法公式")
print("=" * 70)

print("\n經典力學的速度加法:")
print("u = v + u' (錯誤!)")

print("\n相對論的速度加法:")
print("u = (v + u')/(1 + vu'/c²)")

print("\n例子: 兩個都以 0.8c 運動的物體")
u1 = 0.8
u2 = 0.8
u_classical = u1 + u2
u_relativistic = (u1 + u2)/(1 + u1*u2)
print(f"經典預測: {u_classical}c (超光速!錯誤)")
print(f"相對論預測: {u_relativistic:.3f}c (仍然小於光速)")

print("\n" + "=" * 70)
print("9. 四維動量與能量-動量關係")
print("=" * 70)

print("\n四維動量: p^μ = (E/c, p_x, p_y, p_z)")
print("其中 E 是總能量, (p_x, p_y, p_z) 是三維動量")

print("\n不變質量:")
print("p^μ p_μ = -(E/c)² + p² = -(mc)²")
print("因此: E² = (pc)² + (mc²)²")

print("\n對於靜止粒子 (p = 0):")
print("E₀ = mc² (愛因斯坦著名的質能等價公式)")

print("\n對於光子 (m = 0):")
print("E = pc")

print("\n" + "=" * 70)
print("10. 雙生子悖論 (Twin Paradox)")
print("=" * 70)

print("\n情境:")
print("• 雙胞胎 A 留在地球")
print("• 雙胞胎 B 乘太空船以 0.8c 飛行 10 光年然後返回")

print("\n地球參考系:")
v_val = 0.8
gamma_val = 1/sqrt(1 - v_val**2)
distance = 10  # 光年
earth_time = 2 * distance / v_val  # 往返時間
print(f"  往返距離: {2*distance} 光年")
print(f"  往返時間: {earth_time:.1f} 年")

print("\n太空船參考系:")
spaceship_time = earth_time / gamma_val
print(f"  γ = {gamma_val:.3f}")
print(f"  經過時間: {spaceship_time:.1f} 年")

print(f"\n當 B 返回時:")
print(f"  A 老了 {earth_time:.1f} 歲")
print(f"  B 只老了 {spaceship_time:.1f} 歲")
print(f"  年齡差異: {earth_time - spaceship_time:.1f} 年")

print("\n這不是悖論!")
print("因為 B 經歷了加速度(轉向),打破了參考系的對稱性")

print("\n" + "=" * 70)
print("示範完成!")
print("=" * 70)

print("\n摘要:")
print("• 閔可夫斯基時空是狹義相對論的數學框架")
print("• 時空是統一的四維實體,而非獨立的時間和空間")
print("• 洛倫茲變換取代了伽利略變換")
print("• 時間膨脹和長度收縮是真實的物理效應")
print("• 光速在所有慣性參考系中都相同")
print("• 這些效應已被無數實驗證實")
print("\n歷史:")
print("• 1905: 愛因斯坦發表狹義相對論")
print("• 1908: 閔可夫斯基提出四維時空幾何")
print("• 現代物理學的基石,GPS、粒子物理等都需要考慮")