# -*- coding: utf-8 -*-
"""diffgeom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hSuumX7n8KKgbKkAzV_BzpfiHZjrnLkd
"""

"""
SymPy diffgeom 套件示範
展示微分幾何的基本操作
"""

from sympy import symbols, sin, cos, sqrt, simplify, pi, Symbol, atan2
from sympy.diffgeom import Manifold, Patch, CoordSystem, TensorProduct
from sympy.diffgeom import metric_to_Christoffel_2nd, metric_to_Riemann_components

print("=" * 60)
print("1. 建立流形和座標系統")
print("=" * 60)

# 建立 2 維流形
m = Manifold('M', 2)
patch = Patch('P', m)

# 定義笛卡爾座標系統 (使用 Symbol 物件)
x_sym = Symbol('x', real=True)
y_sym = Symbol('y', real=True)
rect = CoordSystem('rect', patch, [x_sym, y_sym])
x, y = rect.coord_functions()

print(f"流形: {m}")
print(f"座標系統: {rect}")
print(f"座標函數: x={x}, y={y}")

print("\n" + "=" * 60)
print("2. 座標基底和對偶基底")
print("=" * 60)

# 座標基底 (切向量)
dx, dy = rect.base_oneforms()
print(f"對偶基底 (1-形式): dx={dx}, dy={dy}")

ex, ey = rect.base_vectors()
print(f"座標基底 (向量場): e_x={ex}, e_y={ey}")

print("\n" + "=" * 60)
print("3. 極座標系統與座標變換")
print("=" * 60)

# 定義極座標系統 (使用 Symbol 物件)
r_sym = Symbol('r', positive=True, real=True)
theta_sym = Symbol('theta', real=True)

# 定義座標變換關係字典
# key 格式: (from_coord_system_name, to_coord_system_name)
# value 格式: [(原座標), (變換後的表達式)]
relations = {
    ('polar', 'rect'): [(r_sym, theta_sym), (r_sym*cos(theta_sym), r_sym*sin(theta_sym))],
    ('rect', 'polar'): [(x_sym, y_sym), (sqrt(x_sym**2 + y_sym**2), atan2(y_sym, x_sym))]
}

# 建立極座標系統
polar = CoordSystem('polar', patch, [r_sym, theta_sym], relations)
r, theta = polar.coord_functions()

print(f"極座標系統: {polar}")
print(f"座標變換: x = r*cos(θ), y = r*sin(θ)")

# 取得極座標的基底
dr, dtheta = polar.base_oneforms()
er, etheta = polar.base_vectors()

print(f"\n極座標基底向量: e_r={er}, e_θ={etheta}")

print("\n" + "=" * 60)
print("4. 度量張量 - 歐幾里得度量")
print("=" * 60)

# 笛卡爾座標的歐幾里得度量: ds² = dx² + dy²
metric_rect = TensorProduct(dx, dx) + TensorProduct(dy, dy)
print(f"笛卡爾座標度量: g = dx⊗dx + dy⊗dy")

# 極座標的度量: ds² = dr² + r²dθ²
metric_polar = TensorProduct(dr, dr) + r**2 * TensorProduct(dtheta, dtheta)
print(f"極座標度量: g = dr⊗dr + r²dθ⊗dθ")

print("\n" + "=" * 60)
print("5. 球面幾何 (2-球面)")
print("=" * 60)

# 建立球面
sphere = Manifold('S^2', 2)
sphere_patch = Patch('U', sphere)

# 使用 Symbol 物件定義球面座標
theta_s_sym = Symbol('theta', real=True)
phi_s_sym = Symbol('phi', real=True)
spherical = CoordSystem('spherical', sphere_patch, [theta_s_sym, phi_s_sym])

theta_s, phi_s = spherical.coord_functions()
dtheta_s, dphi_s = spherical.base_oneforms()

# 球面度量 (半徑為 1): ds² = dθ² + sin²(θ)dφ²
metric_sphere = TensorProduct(dtheta_s, dtheta_s) + \
                sin(theta_s)**2 * TensorProduct(dphi_s, dphi_s)

print("球面座標系統: (θ, φ)")
print("球面度量: ds² = dθ² + sin²(θ)dφ²")

# 計算 Christoffel 符號 (聯絡係數)
print("\n計算 Christoffel 符號...")
christoffel = metric_to_Christoffel_2nd(metric_sphere)

print("\n非零的 Christoffel 符號:")
print(f"Γ^θ_φφ = {simplify(christoffel[0, 1, 1])}")
print(f"Γ^φ_θφ = {simplify(christoffel[1, 0, 1])}")
print(f"Γ^φ_φθ = {simplify(christoffel[1, 1, 0])}")

print("\n" + "=" * 60)
print("6. 計算 Riemann 曲率張量")
print("=" * 60)

# 計算球面的 Riemann 曲率分量
print("計算球面的曲率分量...")
riemann = metric_to_Riemann_components(metric_sphere)

# 顯示一些非零的曲率分量
print("\n關鍵的 Riemann 曲率分量:")
print(f"R^θ_φθφ = {simplify(riemann[0, 1, 0, 1])}")

print("\n" + "=" * 60)
print("7. 向量場操作")
print("=" * 60)

# 在極座標中定義向量場
from sympy.diffgeom import BaseVectorField

# 徑向向量場
v_radial = er
print(f"徑向向量場: v = e_r")

# 旋轉向量場
v_rotation = etheta
print(f"旋轉向量場: v = e_θ")

print("\n" + "=" * 60)
print("8. 1-形式與向量的對偶配對")
print("=" * 60)

# 1-形式作用在向量上
result1 = dr(er)
result2 = dr(etheta)
result3 = dtheta(er)
result4 = dtheta(etheta)

print(f"dr(e_r) = {result1}")
print(f"dr(e_θ) = {result2}")
print(f"dθ(e_r) = {result3}")
print(f"dθ(e_θ) = {result4}")

print("\n" + "=" * 60)
print("示範完成!")
print("=" * 60)
print("\nSymPy diffgeom 主要功能:")
print("• 定義流形、座標系統和座標變換")
print("• 處理切向量場和余切向量場 (1-形式)")
print("• 定義和操作度量張量")
print("• 計算 Christoffel 符號 (聯絡)")
print("• 計算曲率張量 (Riemann, Ricci, 標量曲率)")
print("• 適用於廣義相對論和微分幾何研究")